import '../models/restaurant.dart';
import '../models/travel_times.dart';

class MockData {
  static final List<Restaurant> restaurants = [
    const Restaurant(
      id: '1',
      name: 'Italian Villa',
      cuisine: 'Italian',
      rating: 4.7,
      priceRange: ['\$\$'],
      address: '123 Fifth Ave, Pittsburgh',
      travelTimes: TravelTimes(
        walking: 20,
        biking: 8,
        driving: 5,
      ),
      lat: 40.4406,
      lng: -79.9959,
      imageUrl: 'https://picsum.photos/seed/italian1/400/300',
      isOpenNow: true,
    ),
    const Restaurant(
      id: '2',
      name: 'Panda Express',
      cuisine: 'Chinese',
      rating: 4.0,
      priceRange: ['\$'],
      address: '456 Forbes Ave, Pittsburgh',
      travelTimes: TravelTimes(
        walking: 15,
        biking: 6,
        driving: 4,
      ),
      lat: 40.4406,
      lng: -79.9959,
      imageUrl: 'https://picsum.photos/seed/chinese1/400/300',
      isOpenNow: true,
    ),
    const Restaurant(
      id: '3',
      name: 'Chipotle',
      cuisine: 'Mexican',
      rating: 4.2,
      priceRange: ['\$'],
      address: '789 Oakland Ave, Pittsburgh',
      travelTimes: TravelTimes(
        walking: 25,
        biking: 10,
        driving: 7,
      ),
      lat: 40.4406,
      lng: -79.9959,
      imageUrl: 'https://picsum.photos/seed/mexican1/400/300',
      isOpenNow: true,
    ),
    const Restaurant(
      id: '4',
      name: 'Primanti Bros',
      cuisine: 'American',
      rating: 4.5,
      priceRange: ['\$\$'],
      address: '2100 Carson St, Pittsburgh',
      travelTimes: TravelTimes(
        walking: 30,
        biking: 12,
        driving: 8,
      ),
      lat: 40.4406,
      lng: -79.9959,
      imageUrl: 'https://picsum.photos/seed/american1/400/300',
      isOpenNow: true,
    ),
    const Restaurant(
      id: '5',
      name: 'Taj Mahal',
      cuisine: 'Indian',
      rating: 4.6,
      priceRange: ['\$\$'],
      address: '678 Craig St, Pittsburgh',
      travelTimes: TravelTimes(
        walking: 18,
        biking: 7,
        driving: 5,
      ),
      lat: 40.4406,
      lng: -79.9959,
      imageUrl: 'https://picsum.photos/seed/indian1/400/300',
      isOpenNow: true,
    ),
    const Restaurant(
      id: '6',
      name: 'Sushi Boat',
      cuisine: 'Japanese',
      rating: 4.4,
      priceRange: ['\$\$\$'],
      address: '345 Meyran Ave, Pittsburgh',
      travelTimes: TravelTimes(
        walking: 22,
        biking: 9,
        driving: 6,
      ),
      lat: 40.4406,
      lng: -79.9959,
      imageUrl: 'https://picsum.photos/seed/japanese1/400/300',
      isOpenNow: true,
    ),
    const Restaurant(
      id: '7',
      name: 'Five Guys',
      cuisine: 'American',
      rating: 4.3,
      priceRange: ['\$\$'],
      address: '901 Penn Ave, Pittsburgh',
      travelTimes: TravelTimes(
        walking: 28,
        biking: 11,
        driving: 7,
      ),
      lat: 40.4406,
      lng: -79.9959,
      imageUrl: 'https://picsum.photos/seed/american2/400/300',
      isOpenNow: true,
    ),
    const Restaurant(
      id: '8',
      name: 'Thai Cuisine',
      cuisine: 'Thai',
      rating: 4.5,
      priceRange: ['\$\$'],
      address: '567 Murray Ave, Pittsburgh',
      travelTimes: TravelTimes(
        walking: 35,
        biking: 15,
        driving: 10,
      ),
      lat: 40.4406,
      lng: -79.9959,
      imageUrl: 'https://picsum.photos/seed/thai1/400/300',
      isOpenNow: true,
    ),
  ];

  static final List<String> cuisineTypes = [
    'American',
    'Chinese',
    'Indian',
    'Italian',
    'Japanese',
    'Mexican',
    'Thai',
  ];

  static final List<String> priceRanges = [
    '\$',
    '\$\$',
    '\$\$\$',
  ];
}